env:
  browser: true
root: true
extends:
- airbnb-base
- prettier
plugins:
- prettier
rules:
  prettier/prettier:
  - error
settings:
  import/resolver:
    webpack:
      config: "./webpack.config.js"
